language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - "pip install -U pip"
  - "pip install 'Lektor>=3'"
script: "lektor build"
deploy:
  - provider: script
    script: "lektor deploy staging --username ${DEPLOY_USERNAME} --password ${DEPLOY_SECRET}"
    on:
       branch: develop
  - provider: script
    script: "lektor deploy production --username ${DEPLOY_USERNAME} --password ${DEPLOY_SECRET}"
    on:
       branch: production
